// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace message {

static const char* FinanceService_method_names[] = {
  "/message.FinanceService/CreatePayment",
  "/message.FinanceService/ConfirmPayment",
  "/message.FinanceService/GetPaymentList",
  "/message.FinanceService/GetPaymentDetail",
  "/message.FinanceService/GenerateInvoice",
  "/message.FinanceService/GetInvoiceDetail",
  "/message.FinanceService/GetInvoiceList",
  "/message.FinanceService/GetStatsOverview",
  "/message.FinanceService/GetRevenueStats",
  "/message.FinanceService/GetVehicleStats",
};

std::unique_ptr< FinanceService::Stub> FinanceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FinanceService::Stub> stub(new FinanceService::Stub(channel));
  return stub;
}

FinanceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CreatePayment_(FinanceService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ConfirmPayment_(FinanceService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPaymentList_(FinanceService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPaymentDetail_(FinanceService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GenerateInvoice_(FinanceService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetInvoiceDetail_(FinanceService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetInvoiceList_(FinanceService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStatsOverview_(FinanceService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRevenueStats_(FinanceService_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetVehicleStats_(FinanceService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FinanceService::Stub::CreatePayment(::grpc::ClientContext* context, const ::message::CreatePaymentRequest& request, ::message::PaymentInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreatePayment_, context, request, response);
}

void FinanceService::Stub::experimental_async::CreatePayment(::grpc::ClientContext* context, const ::message::CreatePaymentRequest* request, ::message::PaymentInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreatePayment_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::CreatePayment(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::PaymentInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreatePayment_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::CreatePayment(::grpc::ClientContext* context, const ::message::CreatePaymentRequest* request, ::message::PaymentInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreatePayment_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::CreatePayment(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::PaymentInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreatePayment_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::PaymentInfo>* FinanceService::Stub::AsyncCreatePaymentRaw(::grpc::ClientContext* context, const ::message::CreatePaymentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::PaymentInfo>::Create(channel_.get(), cq, rpcmethod_CreatePayment_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::PaymentInfo>* FinanceService::Stub::PrepareAsyncCreatePaymentRaw(::grpc::ClientContext* context, const ::message::CreatePaymentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::PaymentInfo>::Create(channel_.get(), cq, rpcmethod_CreatePayment_, context, request, false);
}

::grpc::Status FinanceService::Stub::ConfirmPayment(::grpc::ClientContext* context, const ::message::PaymentInfo& request, ::message::PaymentInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ConfirmPayment_, context, request, response);
}

void FinanceService::Stub::experimental_async::ConfirmPayment(::grpc::ClientContext* context, const ::message::PaymentInfo* request, ::message::PaymentInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ConfirmPayment_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::ConfirmPayment(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::PaymentInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ConfirmPayment_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::ConfirmPayment(::grpc::ClientContext* context, const ::message::PaymentInfo* request, ::message::PaymentInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ConfirmPayment_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::ConfirmPayment(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::PaymentInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ConfirmPayment_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::PaymentInfo>* FinanceService::Stub::AsyncConfirmPaymentRaw(::grpc::ClientContext* context, const ::message::PaymentInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::PaymentInfo>::Create(channel_.get(), cq, rpcmethod_ConfirmPayment_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::PaymentInfo>* FinanceService::Stub::PrepareAsyncConfirmPaymentRaw(::grpc::ClientContext* context, const ::message::PaymentInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::PaymentInfo>::Create(channel_.get(), cq, rpcmethod_ConfirmPayment_, context, request, false);
}

::grpc::Status FinanceService::Stub::GetPaymentList(::grpc::ClientContext* context, const ::message::PaymentListRequest& request, ::message::PaymentListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetPaymentList_, context, request, response);
}

void FinanceService::Stub::experimental_async::GetPaymentList(::grpc::ClientContext* context, const ::message::PaymentListRequest* request, ::message::PaymentListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPaymentList_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetPaymentList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::PaymentListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPaymentList_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetPaymentList(::grpc::ClientContext* context, const ::message::PaymentListRequest* request, ::message::PaymentListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPaymentList_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::GetPaymentList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::PaymentListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPaymentList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::PaymentListResponse>* FinanceService::Stub::AsyncGetPaymentListRaw(::grpc::ClientContext* context, const ::message::PaymentListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::PaymentListResponse>::Create(channel_.get(), cq, rpcmethod_GetPaymentList_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::PaymentListResponse>* FinanceService::Stub::PrepareAsyncGetPaymentListRaw(::grpc::ClientContext* context, const ::message::PaymentListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::PaymentListResponse>::Create(channel_.get(), cq, rpcmethod_GetPaymentList_, context, request, false);
}

::grpc::Status FinanceService::Stub::GetPaymentDetail(::grpc::ClientContext* context, const ::message::PaymentInfo& request, ::message::PaymentInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetPaymentDetail_, context, request, response);
}

void FinanceService::Stub::experimental_async::GetPaymentDetail(::grpc::ClientContext* context, const ::message::PaymentInfo* request, ::message::PaymentInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPaymentDetail_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetPaymentDetail(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::PaymentInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPaymentDetail_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetPaymentDetail(::grpc::ClientContext* context, const ::message::PaymentInfo* request, ::message::PaymentInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPaymentDetail_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::GetPaymentDetail(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::PaymentInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPaymentDetail_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::PaymentInfo>* FinanceService::Stub::AsyncGetPaymentDetailRaw(::grpc::ClientContext* context, const ::message::PaymentInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::PaymentInfo>::Create(channel_.get(), cq, rpcmethod_GetPaymentDetail_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::PaymentInfo>* FinanceService::Stub::PrepareAsyncGetPaymentDetailRaw(::grpc::ClientContext* context, const ::message::PaymentInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::PaymentInfo>::Create(channel_.get(), cq, rpcmethod_GetPaymentDetail_, context, request, false);
}

::grpc::Status FinanceService::Stub::GenerateInvoice(::grpc::ClientContext* context, const ::message::GenerateInvoiceRequest& request, ::message::InvoiceInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GenerateInvoice_, context, request, response);
}

void FinanceService::Stub::experimental_async::GenerateInvoice(::grpc::ClientContext* context, const ::message::GenerateInvoiceRequest* request, ::message::InvoiceInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GenerateInvoice_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GenerateInvoice(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::InvoiceInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GenerateInvoice_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GenerateInvoice(::grpc::ClientContext* context, const ::message::GenerateInvoiceRequest* request, ::message::InvoiceInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GenerateInvoice_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::GenerateInvoice(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::InvoiceInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GenerateInvoice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::InvoiceInfo>* FinanceService::Stub::AsyncGenerateInvoiceRaw(::grpc::ClientContext* context, const ::message::GenerateInvoiceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::InvoiceInfo>::Create(channel_.get(), cq, rpcmethod_GenerateInvoice_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::InvoiceInfo>* FinanceService::Stub::PrepareAsyncGenerateInvoiceRaw(::grpc::ClientContext* context, const ::message::GenerateInvoiceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::InvoiceInfo>::Create(channel_.get(), cq, rpcmethod_GenerateInvoice_, context, request, false);
}

::grpc::Status FinanceService::Stub::GetInvoiceDetail(::grpc::ClientContext* context, const ::message::InvoiceInfo& request, ::message::InvoiceInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetInvoiceDetail_, context, request, response);
}

void FinanceService::Stub::experimental_async::GetInvoiceDetail(::grpc::ClientContext* context, const ::message::InvoiceInfo* request, ::message::InvoiceInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceDetail_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetInvoiceDetail(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::InvoiceInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceDetail_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetInvoiceDetail(::grpc::ClientContext* context, const ::message::InvoiceInfo* request, ::message::InvoiceInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceDetail_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::GetInvoiceDetail(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::InvoiceInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceDetail_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::InvoiceInfo>* FinanceService::Stub::AsyncGetInvoiceDetailRaw(::grpc::ClientContext* context, const ::message::InvoiceInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::InvoiceInfo>::Create(channel_.get(), cq, rpcmethod_GetInvoiceDetail_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::InvoiceInfo>* FinanceService::Stub::PrepareAsyncGetInvoiceDetailRaw(::grpc::ClientContext* context, const ::message::InvoiceInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::InvoiceInfo>::Create(channel_.get(), cq, rpcmethod_GetInvoiceDetail_, context, request, false);
}

::grpc::Status FinanceService::Stub::GetInvoiceList(::grpc::ClientContext* context, const ::message::InvoiceListRequest& request, ::message::InvoiceListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetInvoiceList_, context, request, response);
}

void FinanceService::Stub::experimental_async::GetInvoiceList(::grpc::ClientContext* context, const ::message::InvoiceListRequest* request, ::message::InvoiceListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceList_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetInvoiceList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::InvoiceListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceList_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetInvoiceList(::grpc::ClientContext* context, const ::message::InvoiceListRequest* request, ::message::InvoiceListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceList_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::GetInvoiceList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::InvoiceListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::InvoiceListResponse>* FinanceService::Stub::AsyncGetInvoiceListRaw(::grpc::ClientContext* context, const ::message::InvoiceListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::InvoiceListResponse>::Create(channel_.get(), cq, rpcmethod_GetInvoiceList_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::InvoiceListResponse>* FinanceService::Stub::PrepareAsyncGetInvoiceListRaw(::grpc::ClientContext* context, const ::message::InvoiceListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::InvoiceListResponse>::Create(channel_.get(), cq, rpcmethod_GetInvoiceList_, context, request, false);
}

::grpc::Status FinanceService::Stub::GetStatsOverview(::grpc::ClientContext* context, const ::message::CommonResponse& request, ::message::StatsOverviewResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetStatsOverview_, context, request, response);
}

void FinanceService::Stub::experimental_async::GetStatsOverview(::grpc::ClientContext* context, const ::message::CommonResponse* request, ::message::StatsOverviewResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetStatsOverview_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetStatsOverview(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::StatsOverviewResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetStatsOverview_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetStatsOverview(::grpc::ClientContext* context, const ::message::CommonResponse* request, ::message::StatsOverviewResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetStatsOverview_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::GetStatsOverview(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::StatsOverviewResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetStatsOverview_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::StatsOverviewResponse>* FinanceService::Stub::AsyncGetStatsOverviewRaw(::grpc::ClientContext* context, const ::message::CommonResponse& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::StatsOverviewResponse>::Create(channel_.get(), cq, rpcmethod_GetStatsOverview_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::StatsOverviewResponse>* FinanceService::Stub::PrepareAsyncGetStatsOverviewRaw(::grpc::ClientContext* context, const ::message::CommonResponse& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::StatsOverviewResponse>::Create(channel_.get(), cq, rpcmethod_GetStatsOverview_, context, request, false);
}

::grpc::Status FinanceService::Stub::GetRevenueStats(::grpc::ClientContext* context, const ::message::RevenueStatsRequest& request, ::message::RevenueStatsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetRevenueStats_, context, request, response);
}

void FinanceService::Stub::experimental_async::GetRevenueStats(::grpc::ClientContext* context, const ::message::RevenueStatsRequest* request, ::message::RevenueStatsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetRevenueStats_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetRevenueStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::RevenueStatsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetRevenueStats_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetRevenueStats(::grpc::ClientContext* context, const ::message::RevenueStatsRequest* request, ::message::RevenueStatsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetRevenueStats_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::GetRevenueStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::RevenueStatsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetRevenueStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::RevenueStatsResponse>* FinanceService::Stub::AsyncGetRevenueStatsRaw(::grpc::ClientContext* context, const ::message::RevenueStatsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::RevenueStatsResponse>::Create(channel_.get(), cq, rpcmethod_GetRevenueStats_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::RevenueStatsResponse>* FinanceService::Stub::PrepareAsyncGetRevenueStatsRaw(::grpc::ClientContext* context, const ::message::RevenueStatsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::RevenueStatsResponse>::Create(channel_.get(), cq, rpcmethod_GetRevenueStats_, context, request, false);
}

::grpc::Status FinanceService::Stub::GetVehicleStats(::grpc::ClientContext* context, const ::message::CommonResponse& request, ::message::VehicleStatsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetVehicleStats_, context, request, response);
}

void FinanceService::Stub::experimental_async::GetVehicleStats(::grpc::ClientContext* context, const ::message::CommonResponse* request, ::message::VehicleStatsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetVehicleStats_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetVehicleStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::VehicleStatsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetVehicleStats_, context, request, response, std::move(f));
}

void FinanceService::Stub::experimental_async::GetVehicleStats(::grpc::ClientContext* context, const ::message::CommonResponse* request, ::message::VehicleStatsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetVehicleStats_, context, request, response, reactor);
}

void FinanceService::Stub::experimental_async::GetVehicleStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::VehicleStatsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetVehicleStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::VehicleStatsResponse>* FinanceService::Stub::AsyncGetVehicleStatsRaw(::grpc::ClientContext* context, const ::message::CommonResponse& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::VehicleStatsResponse>::Create(channel_.get(), cq, rpcmethod_GetVehicleStats_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::VehicleStatsResponse>* FinanceService::Stub::PrepareAsyncGetVehicleStatsRaw(::grpc::ClientContext* context, const ::message::CommonResponse& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::VehicleStatsResponse>::Create(channel_.get(), cq, rpcmethod_GetVehicleStats_, context, request, false);
}

FinanceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::CreatePaymentRequest, ::message::PaymentInfo>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::CreatePaymentRequest* req,
             ::message::PaymentInfo* resp) {
               return service->CreatePayment(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::PaymentInfo, ::message::PaymentInfo>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::PaymentInfo* req,
             ::message::PaymentInfo* resp) {
               return service->ConfirmPayment(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::PaymentListRequest, ::message::PaymentListResponse>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::PaymentListRequest* req,
             ::message::PaymentListResponse* resp) {
               return service->GetPaymentList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::PaymentInfo, ::message::PaymentInfo>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::PaymentInfo* req,
             ::message::PaymentInfo* resp) {
               return service->GetPaymentDetail(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::GenerateInvoiceRequest, ::message::InvoiceInfo>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::GenerateInvoiceRequest* req,
             ::message::InvoiceInfo* resp) {
               return service->GenerateInvoice(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::InvoiceInfo, ::message::InvoiceInfo>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::InvoiceInfo* req,
             ::message::InvoiceInfo* resp) {
               return service->GetInvoiceDetail(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::InvoiceListRequest, ::message::InvoiceListResponse>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::InvoiceListRequest* req,
             ::message::InvoiceListResponse* resp) {
               return service->GetInvoiceList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::CommonResponse, ::message::StatsOverviewResponse>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::CommonResponse* req,
             ::message::StatsOverviewResponse* resp) {
               return service->GetStatsOverview(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::RevenueStatsRequest, ::message::RevenueStatsResponse>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::RevenueStatsRequest* req,
             ::message::RevenueStatsResponse* resp) {
               return service->GetRevenueStats(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FinanceService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FinanceService::Service, ::message::CommonResponse, ::message::VehicleStatsResponse>(
          [](FinanceService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::CommonResponse* req,
             ::message::VehicleStatsResponse* resp) {
               return service->GetVehicleStats(ctx, req, resp);
             }, this)));
}

FinanceService::Service::~Service() {
}

::grpc::Status FinanceService::Service::CreatePayment(::grpc::ServerContext* context, const ::message::CreatePaymentRequest* request, ::message::PaymentInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FinanceService::Service::ConfirmPayment(::grpc::ServerContext* context, const ::message::PaymentInfo* request, ::message::PaymentInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FinanceService::Service::GetPaymentList(::grpc::ServerContext* context, const ::message::PaymentListRequest* request, ::message::PaymentListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FinanceService::Service::GetPaymentDetail(::grpc::ServerContext* context, const ::message::PaymentInfo* request, ::message::PaymentInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FinanceService::Service::GenerateInvoice(::grpc::ServerContext* context, const ::message::GenerateInvoiceRequest* request, ::message::InvoiceInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FinanceService::Service::GetInvoiceDetail(::grpc::ServerContext* context, const ::message::InvoiceInfo* request, ::message::InvoiceInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FinanceService::Service::GetInvoiceList(::grpc::ServerContext* context, const ::message::InvoiceListRequest* request, ::message::InvoiceListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FinanceService::Service::GetStatsOverview(::grpc::ServerContext* context, const ::message::CommonResponse* request, ::message::StatsOverviewResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FinanceService::Service::GetRevenueStats(::grpc::ServerContext* context, const ::message::RevenueStatsRequest* request, ::message::RevenueStatsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FinanceService::Service::GetVehicleStats(::grpc::ServerContext* context, const ::message::CommonResponse* request, ::message::VehicleStatsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message

