// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace message {

static const char* VehicleService_method_names[] = {
  "/message.VehicleService/GetVehicleList",
  "/message.VehicleService/GetVehicleDetail",
  "/message.VehicleService/AddVehicle",
  "/message.VehicleService/UpdateVehicle",
  "/message.VehicleService/DeleteVehicle",
  "/message.VehicleService/CreateOrder",
  "/message.VehicleService/GetOrderList",
  "/message.VehicleService/GetOrderDetail",
  "/message.VehicleService/PickupVehicle",
  "/message.VehicleService/ReturnVehicle",
  "/message.VehicleService/RenewOrder",
  "/message.VehicleService/CancelOrder",
  "/message.VehicleService/CreateMaintenance",
  "/message.VehicleService/UpdateMaintenance",
  "/message.VehicleService/GetMaintenanceList",
  "/message.VehicleService/DeleteMaintenance",
};

std::unique_ptr< VehicleService::Stub> VehicleService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VehicleService::Stub> stub(new VehicleService::Stub(channel));
  return stub;
}

VehicleService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetVehicleList_(VehicleService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetVehicleDetail_(VehicleService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddVehicle_(VehicleService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateVehicle_(VehicleService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteVehicle_(VehicleService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateOrder_(VehicleService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetOrderList_(VehicleService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetOrderDetail_(VehicleService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PickupVehicle_(VehicleService_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReturnVehicle_(VehicleService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RenewOrder_(VehicleService_method_names[10], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CancelOrder_(VehicleService_method_names[11], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateMaintenance_(VehicleService_method_names[12], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateMaintenance_(VehicleService_method_names[13], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMaintenanceList_(VehicleService_method_names[14], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteMaintenance_(VehicleService_method_names[15], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VehicleService::Stub::GetVehicleList(::grpc::ClientContext* context, const ::message::VehicleListRequest& request, ::message::VehicleListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetVehicleList_, context, request, response);
}

void VehicleService::Stub::experimental_async::GetVehicleList(::grpc::ClientContext* context, const ::message::VehicleListRequest* request, ::message::VehicleListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetVehicleList_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetVehicleList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::VehicleListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetVehicleList_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetVehicleList(::grpc::ClientContext* context, const ::message::VehicleListRequest* request, ::message::VehicleListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetVehicleList_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::GetVehicleList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::VehicleListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetVehicleList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::VehicleListResponse>* VehicleService::Stub::AsyncGetVehicleListRaw(::grpc::ClientContext* context, const ::message::VehicleListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::VehicleListResponse>::Create(channel_.get(), cq, rpcmethod_GetVehicleList_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::VehicleListResponse>* VehicleService::Stub::PrepareAsyncGetVehicleListRaw(::grpc::ClientContext* context, const ::message::VehicleListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::VehicleListResponse>::Create(channel_.get(), cq, rpcmethod_GetVehicleList_, context, request, false);
}

::grpc::Status VehicleService::Stub::GetVehicleDetail(::grpc::ClientContext* context, const ::message::VehicleDetailRequest& request, ::message::VehicleInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetVehicleDetail_, context, request, response);
}

void VehicleService::Stub::experimental_async::GetVehicleDetail(::grpc::ClientContext* context, const ::message::VehicleDetailRequest* request, ::message::VehicleInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetVehicleDetail_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetVehicleDetail(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::VehicleInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetVehicleDetail_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetVehicleDetail(::grpc::ClientContext* context, const ::message::VehicleDetailRequest* request, ::message::VehicleInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetVehicleDetail_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::GetVehicleDetail(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::VehicleInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetVehicleDetail_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::VehicleInfo>* VehicleService::Stub::AsyncGetVehicleDetailRaw(::grpc::ClientContext* context, const ::message::VehicleDetailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::VehicleInfo>::Create(channel_.get(), cq, rpcmethod_GetVehicleDetail_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::VehicleInfo>* VehicleService::Stub::PrepareAsyncGetVehicleDetailRaw(::grpc::ClientContext* context, const ::message::VehicleDetailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::VehicleInfo>::Create(channel_.get(), cq, rpcmethod_GetVehicleDetail_, context, request, false);
}

::grpc::Status VehicleService::Stub::AddVehicle(::grpc::ClientContext* context, const ::message::AddVehicleRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_AddVehicle_, context, request, response);
}

void VehicleService::Stub::experimental_async::AddVehicle(::grpc::ClientContext* context, const ::message::AddVehicleRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_AddVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::AddVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_AddVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::AddVehicle(::grpc::ClientContext* context, const ::message::AddVehicleRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_AddVehicle_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::AddVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_AddVehicle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::AsyncAddVehicleRaw(::grpc::ClientContext* context, const ::message::AddVehicleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_AddVehicle_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::PrepareAsyncAddVehicleRaw(::grpc::ClientContext* context, const ::message::AddVehicleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_AddVehicle_, context, request, false);
}

::grpc::Status VehicleService::Stub::UpdateVehicle(::grpc::ClientContext* context, const ::message::UpdateVehicleRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateVehicle_, context, request, response);
}

void VehicleService::Stub::experimental_async::UpdateVehicle(::grpc::ClientContext* context, const ::message::UpdateVehicleRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::UpdateVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::UpdateVehicle(::grpc::ClientContext* context, const ::message::UpdateVehicleRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateVehicle_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::UpdateVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateVehicle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::AsyncUpdateVehicleRaw(::grpc::ClientContext* context, const ::message::UpdateVehicleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateVehicle_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::PrepareAsyncUpdateVehicleRaw(::grpc::ClientContext* context, const ::message::UpdateVehicleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateVehicle_, context, request, false);
}

::grpc::Status VehicleService::Stub::DeleteVehicle(::grpc::ClientContext* context, const ::message::VehicleDetailRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DeleteVehicle_, context, request, response);
}

void VehicleService::Stub::experimental_async::DeleteVehicle(::grpc::ClientContext* context, const ::message::VehicleDetailRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::DeleteVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::DeleteVehicle(::grpc::ClientContext* context, const ::message::VehicleDetailRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteVehicle_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::DeleteVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteVehicle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::AsyncDeleteVehicleRaw(::grpc::ClientContext* context, const ::message::VehicleDetailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_DeleteVehicle_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::PrepareAsyncDeleteVehicleRaw(::grpc::ClientContext* context, const ::message::VehicleDetailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_DeleteVehicle_, context, request, false);
}

::grpc::Status VehicleService::Stub::CreateOrder(::grpc::ClientContext* context, const ::message::CreateOrderRequest& request, ::message::OrderInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateOrder_, context, request, response);
}

void VehicleService::Stub::experimental_async::CreateOrder(::grpc::ClientContext* context, const ::message::CreateOrderRequest* request, ::message::OrderInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateOrder_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::CreateOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateOrder_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::CreateOrder(::grpc::ClientContext* context, const ::message::CreateOrderRequest* request, ::message::OrderInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateOrder_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::CreateOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::OrderInfo>* VehicleService::Stub::AsyncCreateOrderRaw(::grpc::ClientContext* context, const ::message::CreateOrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderInfo>::Create(channel_.get(), cq, rpcmethod_CreateOrder_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::OrderInfo>* VehicleService::Stub::PrepareAsyncCreateOrderRaw(::grpc::ClientContext* context, const ::message::CreateOrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderInfo>::Create(channel_.get(), cq, rpcmethod_CreateOrder_, context, request, false);
}

::grpc::Status VehicleService::Stub::GetOrderList(::grpc::ClientContext* context, const ::message::OrderListRequest& request, ::message::OrderListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetOrderList_, context, request, response);
}

void VehicleService::Stub::experimental_async::GetOrderList(::grpc::ClientContext* context, const ::message::OrderListRequest* request, ::message::OrderListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetOrderList_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetOrderList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetOrderList_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetOrderList(::grpc::ClientContext* context, const ::message::OrderListRequest* request, ::message::OrderListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetOrderList_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::GetOrderList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetOrderList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::OrderListResponse>* VehicleService::Stub::AsyncGetOrderListRaw(::grpc::ClientContext* context, const ::message::OrderListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderListResponse>::Create(channel_.get(), cq, rpcmethod_GetOrderList_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::OrderListResponse>* VehicleService::Stub::PrepareAsyncGetOrderListRaw(::grpc::ClientContext* context, const ::message::OrderListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderListResponse>::Create(channel_.get(), cq, rpcmethod_GetOrderList_, context, request, false);
}

::grpc::Status VehicleService::Stub::GetOrderDetail(::grpc::ClientContext* context, const ::message::OrderDetailRequest& request, ::message::OrderInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetOrderDetail_, context, request, response);
}

void VehicleService::Stub::experimental_async::GetOrderDetail(::grpc::ClientContext* context, const ::message::OrderDetailRequest* request, ::message::OrderInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetOrderDetail_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetOrderDetail(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetOrderDetail_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetOrderDetail(::grpc::ClientContext* context, const ::message::OrderDetailRequest* request, ::message::OrderInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetOrderDetail_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::GetOrderDetail(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetOrderDetail_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::OrderInfo>* VehicleService::Stub::AsyncGetOrderDetailRaw(::grpc::ClientContext* context, const ::message::OrderDetailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderInfo>::Create(channel_.get(), cq, rpcmethod_GetOrderDetail_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::OrderInfo>* VehicleService::Stub::PrepareAsyncGetOrderDetailRaw(::grpc::ClientContext* context, const ::message::OrderDetailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderInfo>::Create(channel_.get(), cq, rpcmethod_GetOrderDetail_, context, request, false);
}

::grpc::Status VehicleService::Stub::PickupVehicle(::grpc::ClientContext* context, const ::message::PickupRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PickupVehicle_, context, request, response);
}

void VehicleService::Stub::experimental_async::PickupVehicle(::grpc::ClientContext* context, const ::message::PickupRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PickupVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::PickupVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PickupVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::PickupVehicle(::grpc::ClientContext* context, const ::message::PickupRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PickupVehicle_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::PickupVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PickupVehicle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::AsyncPickupVehicleRaw(::grpc::ClientContext* context, const ::message::PickupRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_PickupVehicle_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::PrepareAsyncPickupVehicleRaw(::grpc::ClientContext* context, const ::message::PickupRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_PickupVehicle_, context, request, false);
}

::grpc::Status VehicleService::Stub::ReturnVehicle(::grpc::ClientContext* context, const ::message::ReturnRequest& request, ::message::OrderInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ReturnVehicle_, context, request, response);
}

void VehicleService::Stub::experimental_async::ReturnVehicle(::grpc::ClientContext* context, const ::message::ReturnRequest* request, ::message::OrderInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ReturnVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::ReturnVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ReturnVehicle_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::ReturnVehicle(::grpc::ClientContext* context, const ::message::ReturnRequest* request, ::message::OrderInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ReturnVehicle_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::ReturnVehicle(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ReturnVehicle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::OrderInfo>* VehicleService::Stub::AsyncReturnVehicleRaw(::grpc::ClientContext* context, const ::message::ReturnRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderInfo>::Create(channel_.get(), cq, rpcmethod_ReturnVehicle_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::OrderInfo>* VehicleService::Stub::PrepareAsyncReturnVehicleRaw(::grpc::ClientContext* context, const ::message::ReturnRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderInfo>::Create(channel_.get(), cq, rpcmethod_ReturnVehicle_, context, request, false);
}

::grpc::Status VehicleService::Stub::RenewOrder(::grpc::ClientContext* context, const ::message::RenewRequest& request, ::message::OrderInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RenewOrder_, context, request, response);
}

void VehicleService::Stub::experimental_async::RenewOrder(::grpc::ClientContext* context, const ::message::RenewRequest* request, ::message::OrderInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RenewOrder_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::RenewOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RenewOrder_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::RenewOrder(::grpc::ClientContext* context, const ::message::RenewRequest* request, ::message::OrderInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RenewOrder_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::RenewOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::OrderInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RenewOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::OrderInfo>* VehicleService::Stub::AsyncRenewOrderRaw(::grpc::ClientContext* context, const ::message::RenewRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderInfo>::Create(channel_.get(), cq, rpcmethod_RenewOrder_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::OrderInfo>* VehicleService::Stub::PrepareAsyncRenewOrderRaw(::grpc::ClientContext* context, const ::message::RenewRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::OrderInfo>::Create(channel_.get(), cq, rpcmethod_RenewOrder_, context, request, false);
}

::grpc::Status VehicleService::Stub::CancelOrder(::grpc::ClientContext* context, const ::message::PickupRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CancelOrder_, context, request, response);
}

void VehicleService::Stub::experimental_async::CancelOrder(::grpc::ClientContext* context, const ::message::PickupRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::CancelOrder(::grpc::ClientContext* context, const ::message::PickupRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::AsyncCancelOrderRaw(::grpc::ClientContext* context, const ::message::PickupRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_CancelOrder_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::PrepareAsyncCancelOrderRaw(::grpc::ClientContext* context, const ::message::PickupRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_CancelOrder_, context, request, false);
}

::grpc::Status VehicleService::Stub::CreateMaintenance(::grpc::ClientContext* context, const ::message::CreateMaintenanceRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateMaintenance_, context, request, response);
}

void VehicleService::Stub::experimental_async::CreateMaintenance(::grpc::ClientContext* context, const ::message::CreateMaintenanceRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateMaintenance_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::CreateMaintenance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateMaintenance_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::CreateMaintenance(::grpc::ClientContext* context, const ::message::CreateMaintenanceRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateMaintenance_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::CreateMaintenance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateMaintenance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::AsyncCreateMaintenanceRaw(::grpc::ClientContext* context, const ::message::CreateMaintenanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_CreateMaintenance_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::PrepareAsyncCreateMaintenanceRaw(::grpc::ClientContext* context, const ::message::CreateMaintenanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_CreateMaintenance_, context, request, false);
}

::grpc::Status VehicleService::Stub::UpdateMaintenance(::grpc::ClientContext* context, const ::message::UpdateMaintenanceRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateMaintenance_, context, request, response);
}

void VehicleService::Stub::experimental_async::UpdateMaintenance(::grpc::ClientContext* context, const ::message::UpdateMaintenanceRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateMaintenance_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::UpdateMaintenance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateMaintenance_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::UpdateMaintenance(::grpc::ClientContext* context, const ::message::UpdateMaintenanceRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateMaintenance_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::UpdateMaintenance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateMaintenance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::AsyncUpdateMaintenanceRaw(::grpc::ClientContext* context, const ::message::UpdateMaintenanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateMaintenance_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::PrepareAsyncUpdateMaintenanceRaw(::grpc::ClientContext* context, const ::message::UpdateMaintenanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateMaintenance_, context, request, false);
}

::grpc::Status VehicleService::Stub::GetMaintenanceList(::grpc::ClientContext* context, const ::message::MaintenanceListRequest& request, ::message::MaintenanceListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetMaintenanceList_, context, request, response);
}

void VehicleService::Stub::experimental_async::GetMaintenanceList(::grpc::ClientContext* context, const ::message::MaintenanceListRequest* request, ::message::MaintenanceListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetMaintenanceList_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetMaintenanceList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::MaintenanceListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetMaintenanceList_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::GetMaintenanceList(::grpc::ClientContext* context, const ::message::MaintenanceListRequest* request, ::message::MaintenanceListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetMaintenanceList_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::GetMaintenanceList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::MaintenanceListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetMaintenanceList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::MaintenanceListResponse>* VehicleService::Stub::AsyncGetMaintenanceListRaw(::grpc::ClientContext* context, const ::message::MaintenanceListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::MaintenanceListResponse>::Create(channel_.get(), cq, rpcmethod_GetMaintenanceList_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::MaintenanceListResponse>* VehicleService::Stub::PrepareAsyncGetMaintenanceListRaw(::grpc::ClientContext* context, const ::message::MaintenanceListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::MaintenanceListResponse>::Create(channel_.get(), cq, rpcmethod_GetMaintenanceList_, context, request, false);
}

::grpc::Status VehicleService::Stub::DeleteMaintenance(::grpc::ClientContext* context, const ::message::VehicleDetailRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DeleteMaintenance_, context, request, response);
}

void VehicleService::Stub::experimental_async::DeleteMaintenance(::grpc::ClientContext* context, const ::message::VehicleDetailRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteMaintenance_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::DeleteMaintenance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteMaintenance_, context, request, response, std::move(f));
}

void VehicleService::Stub::experimental_async::DeleteMaintenance(::grpc::ClientContext* context, const ::message::VehicleDetailRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteMaintenance_, context, request, response, reactor);
}

void VehicleService::Stub::experimental_async::DeleteMaintenance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteMaintenance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::AsyncDeleteMaintenanceRaw(::grpc::ClientContext* context, const ::message::VehicleDetailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_DeleteMaintenance_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* VehicleService::Stub::PrepareAsyncDeleteMaintenanceRaw(::grpc::ClientContext* context, const ::message::VehicleDetailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_DeleteMaintenance_, context, request, false);
}

VehicleService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::VehicleListRequest, ::message::VehicleListResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::VehicleListRequest* req,
             ::message::VehicleListResponse* resp) {
               return service->GetVehicleList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::VehicleDetailRequest, ::message::VehicleInfo>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::VehicleDetailRequest* req,
             ::message::VehicleInfo* resp) {
               return service->GetVehicleDetail(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::AddVehicleRequest, ::message::CommonResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::AddVehicleRequest* req,
             ::message::CommonResponse* resp) {
               return service->AddVehicle(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::UpdateVehicleRequest, ::message::CommonResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::UpdateVehicleRequest* req,
             ::message::CommonResponse* resp) {
               return service->UpdateVehicle(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::VehicleDetailRequest, ::message::CommonResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::VehicleDetailRequest* req,
             ::message::CommonResponse* resp) {
               return service->DeleteVehicle(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::CreateOrderRequest, ::message::OrderInfo>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::CreateOrderRequest* req,
             ::message::OrderInfo* resp) {
               return service->CreateOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::OrderListRequest, ::message::OrderListResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::OrderListRequest* req,
             ::message::OrderListResponse* resp) {
               return service->GetOrderList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::OrderDetailRequest, ::message::OrderInfo>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::OrderDetailRequest* req,
             ::message::OrderInfo* resp) {
               return service->GetOrderDetail(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::PickupRequest, ::message::CommonResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::PickupRequest* req,
             ::message::CommonResponse* resp) {
               return service->PickupVehicle(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::ReturnRequest, ::message::OrderInfo>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::ReturnRequest* req,
             ::message::OrderInfo* resp) {
               return service->ReturnVehicle(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::RenewRequest, ::message::OrderInfo>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::RenewRequest* req,
             ::message::OrderInfo* resp) {
               return service->RenewOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::PickupRequest, ::message::CommonResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::PickupRequest* req,
             ::message::CommonResponse* resp) {
               return service->CancelOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::CreateMaintenanceRequest, ::message::CommonResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::CreateMaintenanceRequest* req,
             ::message::CommonResponse* resp) {
               return service->CreateMaintenance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::UpdateMaintenanceRequest, ::message::CommonResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::UpdateMaintenanceRequest* req,
             ::message::CommonResponse* resp) {
               return service->UpdateMaintenance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::MaintenanceListRequest, ::message::MaintenanceListResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::MaintenanceListRequest* req,
             ::message::MaintenanceListResponse* resp) {
               return service->GetMaintenanceList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleService::Service, ::message::VehicleDetailRequest, ::message::CommonResponse>(
          [](VehicleService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::VehicleDetailRequest* req,
             ::message::CommonResponse* resp) {
               return service->DeleteMaintenance(ctx, req, resp);
             }, this)));
}

VehicleService::Service::~Service() {
}

::grpc::Status VehicleService::Service::GetVehicleList(::grpc::ServerContext* context, const ::message::VehicleListRequest* request, ::message::VehicleListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::GetVehicleDetail(::grpc::ServerContext* context, const ::message::VehicleDetailRequest* request, ::message::VehicleInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::AddVehicle(::grpc::ServerContext* context, const ::message::AddVehicleRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::UpdateVehicle(::grpc::ServerContext* context, const ::message::UpdateVehicleRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::DeleteVehicle(::grpc::ServerContext* context, const ::message::VehicleDetailRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::CreateOrder(::grpc::ServerContext* context, const ::message::CreateOrderRequest* request, ::message::OrderInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::GetOrderList(::grpc::ServerContext* context, const ::message::OrderListRequest* request, ::message::OrderListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::GetOrderDetail(::grpc::ServerContext* context, const ::message::OrderDetailRequest* request, ::message::OrderInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::PickupVehicle(::grpc::ServerContext* context, const ::message::PickupRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::ReturnVehicle(::grpc::ServerContext* context, const ::message::ReturnRequest* request, ::message::OrderInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::RenewOrder(::grpc::ServerContext* context, const ::message::RenewRequest* request, ::message::OrderInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::CancelOrder(::grpc::ServerContext* context, const ::message::PickupRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::CreateMaintenance(::grpc::ServerContext* context, const ::message::CreateMaintenanceRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::UpdateMaintenance(::grpc::ServerContext* context, const ::message::UpdateMaintenanceRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::GetMaintenanceList(::grpc::ServerContext* context, const ::message::MaintenanceListRequest* request, ::message::MaintenanceListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleService::Service::DeleteMaintenance(::grpc::ServerContext* context, const ::message::VehicleDetailRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message

