// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace message {

static const char* UserService_method_names[] = {
  "/message.UserService/UserRegister",
  "/message.UserService/UserLogin",
  "/message.UserService/GetUserProfile",
  "/message.UserService/UpdateProfile",
  "/message.UserService/GetUserList",
  "/message.UserService/UpdateUserStatus",
  "/message.UserService/UpdateUserRole",
  "/message.UserService/GetBalance",
  "/message.UserService/TopupBalance",
  "/message.UserService/GetBalanceRecords",
};

std::unique_ptr< UserService::Stub> UserService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserService::Stub> stub(new UserService::Stub(channel));
  return stub;
}

UserService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_UserRegister_(UserService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UserLogin_(UserService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUserProfile_(UserService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateProfile_(UserService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUserList_(UserService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateUserStatus_(UserService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateUserRole_(UserService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBalance_(UserService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TopupBalance_(UserService_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBalanceRecords_(UserService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserService::Stub::UserRegister(::grpc::ClientContext* context, const ::message::UserRegisterRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UserRegister_, context, request, response);
}

void UserService::Stub::experimental_async::UserRegister(::grpc::ClientContext* context, const ::message::UserRegisterRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UserRegister_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UserRegister(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UserRegister_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UserRegister(::grpc::ClientContext* context, const ::message::UserRegisterRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UserRegister_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::UserRegister(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UserRegister_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::AsyncUserRegisterRaw(::grpc::ClientContext* context, const ::message::UserRegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UserRegister_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::PrepareAsyncUserRegisterRaw(::grpc::ClientContext* context, const ::message::UserRegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UserRegister_, context, request, false);
}

::grpc::Status UserService::Stub::UserLogin(::grpc::ClientContext* context, const ::message::UserLoginRequest& request, ::message::UserLoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UserLogin_, context, request, response);
}

void UserService::Stub::experimental_async::UserLogin(::grpc::ClientContext* context, const ::message::UserLoginRequest* request, ::message::UserLoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UserLogin_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UserLogin(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::UserLoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UserLogin_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UserLogin(::grpc::ClientContext* context, const ::message::UserLoginRequest* request, ::message::UserLoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UserLogin_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::UserLogin(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::UserLoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UserLogin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::UserLoginResponse>* UserService::Stub::AsyncUserLoginRaw(::grpc::ClientContext* context, const ::message::UserLoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::UserLoginResponse>::Create(channel_.get(), cq, rpcmethod_UserLogin_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::UserLoginResponse>* UserService::Stub::PrepareAsyncUserLoginRaw(::grpc::ClientContext* context, const ::message::UserLoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::UserLoginResponse>::Create(channel_.get(), cq, rpcmethod_UserLogin_, context, request, false);
}

::grpc::Status UserService::Stub::GetUserProfile(::grpc::ClientContext* context, const ::message::UserProfileRequest& request, ::message::UserProfileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetUserProfile_, context, request, response);
}

void UserService::Stub::experimental_async::GetUserProfile(::grpc::ClientContext* context, const ::message::UserProfileRequest* request, ::message::UserProfileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::GetUserProfile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::UserProfileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::GetUserProfile(::grpc::ClientContext* context, const ::message::UserProfileRequest* request, ::message::UserProfileResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::GetUserProfile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::UserProfileResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::UserProfileResponse>* UserService::Stub::AsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::message::UserProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::UserProfileResponse>::Create(channel_.get(), cq, rpcmethod_GetUserProfile_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::UserProfileResponse>* UserService::Stub::PrepareAsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::message::UserProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::UserProfileResponse>::Create(channel_.get(), cq, rpcmethod_GetUserProfile_, context, request, false);
}

::grpc::Status UserService::Stub::UpdateProfile(::grpc::ClientContext* context, const ::message::UpdateProfileRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateProfile_, context, request, response);
}

void UserService::Stub::experimental_async::UpdateProfile(::grpc::ClientContext* context, const ::message::UpdateProfileRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateProfile_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UpdateProfile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateProfile_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UpdateProfile(::grpc::ClientContext* context, const ::message::UpdateProfileRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateProfile_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::UpdateProfile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::AsyncUpdateProfileRaw(::grpc::ClientContext* context, const ::message::UpdateProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateProfile_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::PrepareAsyncUpdateProfileRaw(::grpc::ClientContext* context, const ::message::UpdateProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateProfile_, context, request, false);
}

::grpc::Status UserService::Stub::GetUserList(::grpc::ClientContext* context, const ::message::UserListRequest& request, ::message::UserListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetUserList_, context, request, response);
}

void UserService::Stub::experimental_async::GetUserList(::grpc::ClientContext* context, const ::message::UserListRequest* request, ::message::UserListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetUserList_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::GetUserList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::UserListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetUserList_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::GetUserList(::grpc::ClientContext* context, const ::message::UserListRequest* request, ::message::UserListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetUserList_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::GetUserList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::UserListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetUserList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::UserListResponse>* UserService::Stub::AsyncGetUserListRaw(::grpc::ClientContext* context, const ::message::UserListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::UserListResponse>::Create(channel_.get(), cq, rpcmethod_GetUserList_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::UserListResponse>* UserService::Stub::PrepareAsyncGetUserListRaw(::grpc::ClientContext* context, const ::message::UserListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::UserListResponse>::Create(channel_.get(), cq, rpcmethod_GetUserList_, context, request, false);
}

::grpc::Status UserService::Stub::UpdateUserStatus(::grpc::ClientContext* context, const ::message::UpdateUserStatusRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateUserStatus_, context, request, response);
}

void UserService::Stub::experimental_async::UpdateUserStatus(::grpc::ClientContext* context, const ::message::UpdateUserStatusRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateUserStatus_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UpdateUserStatus(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateUserStatus_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UpdateUserStatus(::grpc::ClientContext* context, const ::message::UpdateUserStatusRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateUserStatus_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::UpdateUserStatus(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateUserStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::AsyncUpdateUserStatusRaw(::grpc::ClientContext* context, const ::message::UpdateUserStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateUserStatus_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::PrepareAsyncUpdateUserStatusRaw(::grpc::ClientContext* context, const ::message::UpdateUserStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateUserStatus_, context, request, false);
}

::grpc::Status UserService::Stub::UpdateUserRole(::grpc::ClientContext* context, const ::message::UpdateUserRoleRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateUserRole_, context, request, response);
}

void UserService::Stub::experimental_async::UpdateUserRole(::grpc::ClientContext* context, const ::message::UpdateUserRoleRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateUserRole_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UpdateUserRole(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateUserRole_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::UpdateUserRole(::grpc::ClientContext* context, const ::message::UpdateUserRoleRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateUserRole_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::UpdateUserRole(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateUserRole_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::AsyncUpdateUserRoleRaw(::grpc::ClientContext* context, const ::message::UpdateUserRoleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateUserRole_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::PrepareAsyncUpdateUserRoleRaw(::grpc::ClientContext* context, const ::message::UpdateUserRoleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_UpdateUserRole_, context, request, false);
}

::grpc::Status UserService::Stub::GetBalance(::grpc::ClientContext* context, const ::message::GetBalanceRequest& request, ::message::GetBalanceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetBalance_, context, request, response);
}

void UserService::Stub::experimental_async::GetBalance(::grpc::ClientContext* context, const ::message::GetBalanceRequest* request, ::message::GetBalanceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetBalance_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::GetBalance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::GetBalanceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetBalance_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::GetBalance(::grpc::ClientContext* context, const ::message::GetBalanceRequest* request, ::message::GetBalanceResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetBalance_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::GetBalance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::GetBalanceResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetBalance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::GetBalanceResponse>* UserService::Stub::AsyncGetBalanceRaw(::grpc::ClientContext* context, const ::message::GetBalanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::GetBalanceResponse>::Create(channel_.get(), cq, rpcmethod_GetBalance_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::GetBalanceResponse>* UserService::Stub::PrepareAsyncGetBalanceRaw(::grpc::ClientContext* context, const ::message::GetBalanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::GetBalanceResponse>::Create(channel_.get(), cq, rpcmethod_GetBalance_, context, request, false);
}

::grpc::Status UserService::Stub::TopupBalance(::grpc::ClientContext* context, const ::message::TopupRequest& request, ::message::CommonResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TopupBalance_, context, request, response);
}

void UserService::Stub::experimental_async::TopupBalance(::grpc::ClientContext* context, const ::message::TopupRequest* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TopupBalance_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::TopupBalance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TopupBalance_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::TopupBalance(::grpc::ClientContext* context, const ::message::TopupRequest* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TopupBalance_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::TopupBalance(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::CommonResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TopupBalance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::AsyncTopupBalanceRaw(::grpc::ClientContext* context, const ::message::TopupRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_TopupBalance_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::CommonResponse>* UserService::Stub::PrepareAsyncTopupBalanceRaw(::grpc::ClientContext* context, const ::message::TopupRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::CommonResponse>::Create(channel_.get(), cq, rpcmethod_TopupBalance_, context, request, false);
}

::grpc::Status UserService::Stub::GetBalanceRecords(::grpc::ClientContext* context, const ::message::BalanceRecordListRequest& request, ::message::BalanceRecordListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetBalanceRecords_, context, request, response);
}

void UserService::Stub::experimental_async::GetBalanceRecords(::grpc::ClientContext* context, const ::message::BalanceRecordListRequest* request, ::message::BalanceRecordListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetBalanceRecords_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::GetBalanceRecords(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::BalanceRecordListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetBalanceRecords_, context, request, response, std::move(f));
}

void UserService::Stub::experimental_async::GetBalanceRecords(::grpc::ClientContext* context, const ::message::BalanceRecordListRequest* request, ::message::BalanceRecordListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetBalanceRecords_, context, request, response, reactor);
}

void UserService::Stub::experimental_async::GetBalanceRecords(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::BalanceRecordListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetBalanceRecords_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::BalanceRecordListResponse>* UserService::Stub::AsyncGetBalanceRecordsRaw(::grpc::ClientContext* context, const ::message::BalanceRecordListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::BalanceRecordListResponse>::Create(channel_.get(), cq, rpcmethod_GetBalanceRecords_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::BalanceRecordListResponse>* UserService::Stub::PrepareAsyncGetBalanceRecordsRaw(::grpc::ClientContext* context, const ::message::BalanceRecordListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::BalanceRecordListResponse>::Create(channel_.get(), cq, rpcmethod_GetBalanceRecords_, context, request, false);
}

UserService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::UserRegisterRequest, ::message::CommonResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::UserRegisterRequest* req,
             ::message::CommonResponse* resp) {
               return service->UserRegister(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::UserLoginRequest, ::message::UserLoginResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::UserLoginRequest* req,
             ::message::UserLoginResponse* resp) {
               return service->UserLogin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::UserProfileRequest, ::message::UserProfileResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::UserProfileRequest* req,
             ::message::UserProfileResponse* resp) {
               return service->GetUserProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::UpdateProfileRequest, ::message::CommonResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::UpdateProfileRequest* req,
             ::message::CommonResponse* resp) {
               return service->UpdateProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::UserListRequest, ::message::UserListResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::UserListRequest* req,
             ::message::UserListResponse* resp) {
               return service->GetUserList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::UpdateUserStatusRequest, ::message::CommonResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::UpdateUserStatusRequest* req,
             ::message::CommonResponse* resp) {
               return service->UpdateUserStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::UpdateUserRoleRequest, ::message::CommonResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::UpdateUserRoleRequest* req,
             ::message::CommonResponse* resp) {
               return service->UpdateUserRole(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::GetBalanceRequest, ::message::GetBalanceResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::GetBalanceRequest* req,
             ::message::GetBalanceResponse* resp) {
               return service->GetBalance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::TopupRequest, ::message::CommonResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::TopupRequest* req,
             ::message::CommonResponse* resp) {
               return service->TopupBalance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::message::BalanceRecordListRequest, ::message::BalanceRecordListResponse>(
          [](UserService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::BalanceRecordListRequest* req,
             ::message::BalanceRecordListResponse* resp) {
               return service->GetBalanceRecords(ctx, req, resp);
             }, this)));
}

UserService::Service::~Service() {
}

::grpc::Status UserService::Service::UserRegister(::grpc::ServerContext* context, const ::message::UserRegisterRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::UserLogin(::grpc::ServerContext* context, const ::message::UserLoginRequest* request, ::message::UserLoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::GetUserProfile(::grpc::ServerContext* context, const ::message::UserProfileRequest* request, ::message::UserProfileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::UpdateProfile(::grpc::ServerContext* context, const ::message::UpdateProfileRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::GetUserList(::grpc::ServerContext* context, const ::message::UserListRequest* request, ::message::UserListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::UpdateUserStatus(::grpc::ServerContext* context, const ::message::UpdateUserStatusRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::UpdateUserRole(::grpc::ServerContext* context, const ::message::UpdateUserRoleRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::GetBalance(::grpc::ServerContext* context, const ::message::GetBalanceRequest* request, ::message::GetBalanceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::TopupBalance(::grpc::ServerContext* context, const ::message::TopupRequest* request, ::message::CommonResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::GetBalanceRecords(::grpc::ServerContext* context, const ::message::BalanceRecordListRequest* request, ::message::BalanceRecordListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message

